import { Box, Plus } from "lucide-react";
import Link from "next/link";
import { AdminPageHeader, EmptyState, Notice, StatusBadge } from "@/components/admin/admin-ui";
import { getAdminItems } from "@/lib/admin-data";
import { formatDate } from "@/lib/utils";

export default async function AdminItemsPage({ searchParams }: { searchParams: Promise<{ deleted?: string }> }) {
  const [items, query] = await Promise.all([getAdminItems(), searchParams]);
  return <div className="mx-auto max-w-6xl">{query.deleted ? <Notice type="deleted" /> : null}<AdminPageHeader eyebrow="Contenido" title="Objetos" description="Fichas detalladas enlazadas a sus mods." action={<Link href="/admin/items/nuevo" className="inline-flex min-h-11 items-center gap-2 bg-[#08749a] px-5 text-sm font-black text-white"><Plus className="size-4" /> Nuevo objeto</Link>} />{items.length ? <div className="mt-7 overflow-x-auto border border-[#d5dfdc] bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-[#09202c] text-[0.65rem] uppercase tracking-[0.12em] text-white/55"><tr><th className="px-5 py-3">Objeto</th><th className="px-4 py-3">Mod</th><th className="px-4 py-3">Durabilidad</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Actualizado</th><th className="px-5 py-3 text-right">Acción</th></tr></thead><tbody className="divide-y divide-[#e1e9e7]">{items.map((item) => <tr key={item.id} className="hover:bg-[#f3f8f6]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center bg-[#dff2f0] text-[#08749a]"><Box className="size-4" /></span><span><strong className="block">{item.name}</strong><span className="text-xs text-[#7f9298]">/{item.slug}</span></span></div></td><td className="px-4 py-4 font-semibold text-[#55707a]">{item.modTitle}</td><td className="px-4 py-4 text-[#55707a]">{item.durability ?? "No aplica"}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-4 py-4 text-xs text-[#6b8088]">{formatDate(item.updatedAt)}</td><td className="px-5 py-4 text-right"><Link href={`/admin/items/${item.id}`} className="font-black text-[#08749a] hover:underline">Editar</Link></td></tr>)}</tbody></table></div> : <EmptyState>No hay objetos todavía.</EmptyState>}</div>;
}
